sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_8845e5887ae6_key -iv $encrypted_8845e5887ae6_iv -in multi-k8s-285406-ac653c1fba3c.json.enc -out multi-k8s-285406-ac653c1fba3c.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    